### ISSUE TITLE
Criação página sobre

### ISSUE THREAD

**Issue by cristianosantossjc** [cris-lexcris/github-master#3]
gostaria de saber sobre o projeot

**Comment by cris-lexcris** [comment]
pagina em producao

**Comment by cristianosantossjc** [comment]
Obrigado no aguardo

2018-02-07 19:49 GMT-02:00 Cristiano Santos <notifications@github.com>:

**Comment by cristianosantossjc** [comment]
@cris-lexcris falta o tel
